#%RAML 1.0 DataType

type: any
examples:
  locationName: string
  crsCode: string
  estimatedTime: string
  reason?: string
  serviceType: string
  serviceId: string
  origin: string
  destination: string
  
