#%RAML 1.0 Library
usage:

types:
    CustomerType: !include DataTypes/CustomerType.raml
    CustomerIdType: !include DataTypes/CustomerIdType.raml
    SubscriptionType: !include DataTypes/SubscriptionType.raml
    SubscriptionIdType: !include DataTypes/SubscriptionIdType.raml
    AlertType: !include DataTypes/AlertsType.raml
    AlertIdType: !include DataTypes/AlertIdType.raml
    CustomerAuthType: !include DataTypes/CustomerAuthType.raml
    DelayServicesType: !include DataTypes/DelayServicesType.raml
    UserUpdateType: !include DataTypes/UserUpdateType.raml
    CustomerAuthDetailsType: !include DataTypes/CustomerAuthDetailsType.raml
    PasswordType: !include DataTypes/PasswordType.raml