#%RAML 1.0 DataType

type: any
examples:
  customerId?: integer
  firstName: string
  lastName: string
  emailId: string
  phoneNo: string
  statusTypeId?: integer
  creationDate?: date-only
  createdBy?: string
  lastUpdatedDate?: date-only
  lastUpdatedBy?: string