#%RAML 1.0 NamedExample
value:

  -
    locationName: "London Bridge"
    crs: "LBG"
    estimatedTime: "06:11"
    reason: "This train has been delayed by a broken down train earlier today"
    serviceType: "train"
    serviceId: "bdBxFFF/vGsmaFJW+C6d6A=="
    origin: "Crayford"
    destination: "London Cannon Street"

  -
    locationName: "London Bridge"
    crs: "LBG"
    estimatedTime: "ontime"
    serviceType: "train"
    serviceId: "vGKlViTeqxQ604+oQeEukg=="
    origin: "London Cannon Street"
    destination: "Slade Green"
  
