#%RAML 1.0 NamedExample
value:

  -
    firstName: "Lahari"
    lastName: "Dinta"
    emailId: "laharidinta@gamil.com"
    phoneNo: "8976543210"

  -
    firstName: "Teja"
    lastName: "Dinta"
    emailId: "tejadinta@gamil.com"
    phoneNo: "8976546510"
    statusTypeId: 1