#%RAML 1.0 NamedExample
value:

  -
    subscriptionId: 234
    customerId: 124
    serviceId: "0019"
    fromTime: 07:18:00
    fromStation: Abbey Wood [ABW]
    toStation: Caersws [CWS]
    toTime: 12:11:00
    journeyDate: 2021-05-09
    advanceNotifyTime: 60
    alertService: yes
    statusTypeId: 1
    creationDate: 2021-05-09
    createdBy: "Teja"
    lastUpdatedDate: 2021-05-10
    lastUpdatedBy: "Teja"
