#%RAML 1.0 NamedExample
value:

  -
    alertId: 265
    subscriptionId: 146
    emailNotify: "yes"
    originLocation: "LBG"
    destinationLocation: "CST"
    serviceType: "train"
    serviceId: "vGKlViTeqxQ604+oEukg=="
    delayStatus: "delay"
    delayTime: 3
    trainDelayReason: "Delayed"
    statusTypeId: 1
    creationDate: 2021-05-09
    createdBy: "Lahari"
    lastUpdatedDate: 2021-05-10
    lastUpdatedBy: "Lahari"