#%RAML 1.0 NamedExample
value:

  -
    alertId: 212
    subscriptionId: 145
    emailNotify: "yes"
    originLocation: "LBGt"
    destinationLocation: "CST"
    serviceType: "train"
    serviceId: "vGKlViTeqxQ604+oQeEukg=="
    delayStatus: "delay"
    delayTime: 3
    trainDelayReason: "Delayed"
    statusTypeId: 1
    creationDate: 2021-05-09
    createdBy: "Lahari"
    lastUpdatedDate: 2021-05-10
    lastUpdatedBy: "Lahari"

  -
    alertId: 213
    subscriptionId: 145
    emailNotify: "yes"
    originLocation: "ABW"
    destinationLocation: "CES"
    serviceType: "train"
    serviceId: "vGKlViTeqxQ604+oEukg=="
    delayStatus: "delay"
    delayTime: 3
    trainDelayReason: "Delayed"
    statusTypeId: 1
    creationDate: 2021-05-09
    createdBy: "Lahari"
    lastUpdatedDate: 2021-05-10
    lastUpdatedBy: "Lahari"