#%RAML 1.0 NamedExample
value:

  -
    subscriptionId: 145
    customerId: 123
    serviceId: "0009"
    fromTime: 07:18:00
    fromStation: Abbey Wood [ABW]
    toStation: Caersws [CWS]
    toTime: 12:11:00
    journeyDate: 2021-05-09
    serviceType: "train"
    alertService: yes
    statusTypeId: 1
    creationDate: 2021-05-09
    createdBy: "Lahari"
    lastUpdatedDate: 2021-05-10
    lastUpdatedBy: "Lahari"

  -
    subscriptionId: 146
    customerId: 123
    fromTime: 15:18:00
    fromStation: Caersws [CWS]
    toStation: Abbey Wood [ABW]
    toTime: 20:14:00
    journeyDate: 2021-05-09
    serviceType: "train"
    route: "via Greenwich"
    advanceNotifyTime: 15
    alertService: yes
    statusTypeId: 1
    creationDate: 2021-05-09
    createdBy: "Lahari"
    lastUpdatedDate: 2021-05-10
    lastUpdatedBy: "Lahari"