#%RAML 1.0 NamedExample
value:

  -
    customerId: 123
    firstName: "Lahari"
    lastName: "Dinta"
    emailId: "laharidinta@gamil.com"
    phoneNo: "8976543210"
    statusTypeId: 1
    creationDate: 2017-05-23
    createdBy: "Lahari"
    lastUpdatedDate: 2019-03-21
    lastUpdatedBy: "Lahari"

  -
    customerId: 124
    firstName: "Teja"
    lastName: "Dinta"
    emailId: "tejadinta@gamil.com"
    phoneNo: "8976546510"
    statusTypeId: 1
    creationDate: 2018-10-23
    createdBy: "Teja"
    lastUpdatedDate: 2019-12-12
    lastUpdatedBy: "Teja"