#%RAML 1.0 DataType

type: any
example:
  alertId?: integer
  subscriptionId?: integer
  emailNotify?: string
  originLocation: string
  destinationLocation: string
  serviceType: string
  serviceId: string
  delayStatus: string
  delayTime: integer
  trainDelayReason: string
  statusTypeId?: integer
  creationDate?: date-only
  createdBy?: string
  lastUpdatedDate?: date-only
  lastUpdatedBy?: string